### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [rikharink/zsh-personal-qol#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by rikharink** [comment]
This is just a plugin for personal use (that's public so my collegues can easily check it out) So don't think it is of much use in a awesome-list.

**Comment by unixorn** [comment]
Ok. If you ever change your mind, file a PR or an issue on the list repo :-)
